name: CI
on: [push, pull_request]
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  ci:
    uses: york-fs/monorepo/.github/workflows/kicad.yml@866463ed08085ee72aa10930fd3d2ad9d062740a
